- name: Use docker compose to run all containers
  hosts: local
  tasks:
    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: 
          - "docker==6.1.3"
          - "docker-compose"

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: ./
        
    - name: Run docker compose up command
      docker_compose:
        project_src: ./
        state: present
        pull: yes
